name: Build and Deploy
on: 
  workflow_dispatch: 
permissions:
  contents: read
  security-events: write
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: npm audit
        run: |
          npm install
          npm audit --audit-level=moderate
      - name: Build image
        run: |
          docker build -t myapp:latest .
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Login2ACR
        uses: azure/docker-login@v1
        with:
          login-server: labdeployacrjeremy.azurecr.io
          username: ${{ secrets.ACR_USER }}
          password: ${{secrets.ACR_PWD}}
      - name: Push to ACR
        run: |
          docker tag myapp:latest labdeployacrjeremy.azurecr.io/myapp:latest
          docker push labdeployacrjeremy.azurecr.io/myapp:latest
      - name: Deploy to WebApp
        run: |
          az webapp config container set \
          -g RGLabDeploy-Jeremy \
          -n labdeploy-webapp-Jeremy \
          --container-image-name labdeployacrjeremy.azurecr.io/myapp:latest \
          --container-registry-url https://labdeployacrjeremy.azurecr.io \
          --container-registry-user ${{secrets.ACR_USER}} \
          --container-registry-password ${{secrets.ACR_PWD}}    
